### ISSUE TITLE
RPC Error leaving venerable file behind

### ISSUE THREAD

**Issue by sfawcett123** [cloudfoundry-community/terraform-provider-cloudfoundry#281] opened 2020-09-17 08:52 UTC
On two of our projects, we have two different deployments into two different cloud-foundry spaces. ( totally independent of one another  ) we occasionally receive an RCP error. The RPC error then leaves a copy of the {application}-venerable behind, and the next deployment fails with unable to rename.

We deploy a docker image using Blue-green strategy:

```
resource "cloudfoundry_app" "app_application" {
    name         = var.paas_app_application_name
    space        = data.cloudfoundry_space.space.id
    docker_image = 'dfedigital/get-into-teaching-frontend:xxxxx' 
    strategy     = 'blue-green'
    memory       = 1024
    dynamic "service_binding" {
      for_each = data.cloudfoundry_user_provided_service.logging
      content {
        service_instance = service_binding.value["id"]
      }
    }

    service_binding  {
            service_instance = cloudfoundry_service_instance.redis.id
    }

    routes { route = cloudfoundry_route.app_route_internal.id }
    dynamic "routes" {
      for_each = data.cloudfoundry_route.app_route_internet
      content {
        route = routes.value["id"]
      }
    }
    environment = {
           REDACTED
    }
}
```

The first error we see is :
```
2020-09-16T12:59:53.5402571Z Acquiring state lock. This may take a few moments...
2020-09-16T12:59:56.5157282Z [0m[1mcloudfoundry_app.app_application: Modifying... [id=98341e16-a9e8-4145-a616-944ceae9ca66][0m[0m
2020-09-16T13:00:06.5162640Z [0m[1mcloudfoundry_app.app_application: Still modifying... [id=98341e16-a9e8-4145-a616-944ceae9ca66, 10s elapsed][0m[0m
2020-09-16T13:00:16.5163191Z [0m[1mcloudfoundry_app.app_application: Still modifying... [id=98341e16-a9e8-4145-a616-944ceae9ca66, 20s elapsed][0m[0m
2020-09-16T13:00:26.5167126Z [0m[1mcloudfoundry_app.app_application: Still modifying... [id=98341e16-a9e8-4145-a616-944ceae9ca66, 30s elapsed][0m[0m
2020-09-16T13:00:36.5169889Z [0m[1mcloudfoundry_app.app_application: Still modifying... [id=98341e16-a9e8-4145-a616-944ceae9ca66, 40s elapsed][0m[0m
2020-09-16T13:00:47.2564896Z [0m[1mcloudfoundry_app.app_application: Still modifying... [id=98341e16-a9e8-4145-a616-944ceae9ca66, 50s elapsed][0m[0m
2020-09-16T13:00:56.5171045Z [0m[1mcloudfoundry_app.app_application: Still modifying... [id=98341e16-a9e8-4145-a616-944ceae9ca66, 1m0s elapsed][0m[0m
2020-09-16T13:01:06.5172704Z [0m[1mcloudfoundry_app.app_application: Still modifying... [id=98341e16-a9e8-4145-a616-944ceae9ca66, 1m10s elapsed][0m[0m
2020-09-16T13:01:16.5173479Z [0m[1mcloudfoundry_app.app_application: Still modifying... [id=98341e16-a9e8-4145-a616-944ceae9ca66, 1m20s elapsed][0m[0m
2020-09-16T13:01:17.3971991Z [31m
2020-09-16T13:01:17.3973296Z [1m[31mError: [0m[0m[1mrpc error: code = Unavailable desc = transport is closing[0m
2020-09-16T13:01:18.7637852Z 
2020-09-16T13:01:18.7640093Z [0m[0m[0m
```

[logs_1164.zip](https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/files/5237606/logs_1164.zip)

Then after that we start to see the following errors on subsequent deployments:
```
2020-09-16T13:11:00.9178179Z [1m[31mError: [0m[0m[1mOh no. Something's gone wrong. I've tried to roll back but you should check to see if everything is OK.: The app name is taken: ***[0m
2020-09-16T13:11:00.9178910Z 
2020-09-16T13:11:00.9179938Z [0m  on application.tf line 1, in resource "cloudfoundry_app" "app_application":
2020-09-16T13:11:00.9181862Z    1: resource "cloudfoundry_app" "app_application" [4m{[0m
2020-09-16T13:11:00.9182525Z [0m
2020-09-16T13:11:00.9183276Z [0m[0m
```

[logs_1165.zip](https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/files/5237631/logs_1165.zip)

If we delete the application, then rename venerable back to the application name, we can keep the system available and subsequent deployments start to work.

The initial problem seems to be a RPC error, which I cannot trace. but could it be possible to retry if that happens.

Subsequently we have the <application>-venerable left, can that be deleted?

**Comment by 46bit** [comment] 2020-09-24 16:36
We believe that the `logs_1164.zip` error above was caused by the app push timing out after one minute. I've filed #282 to document the default timeouts.

This issue is now about why they're seeing the `rpc error` messages instead of the friendly error messages.

**Comment by ArthurHlt** [comment] 2020-09-25 08:31
@sfawcett123 

The app timeout is the timeout to wait until an app is started but staging, pushing, retrieving from a docker registry is not included in this time so I don't think this is related. Actually, this is the same behaviour as the cli does (cli v6 at least).

If an error timeout occurred in this case you should not have an rpc error like that. And the time you get before get an  error is a little to short to be associated to app timeout.

Anyway it needs to be debuggued, Could you create trace by exporting env var `TF_LOG=trace` ? this can help to see why connection has been closed abruptedly. 

@46bit thanks for the PR it's always better to have clear doc

**Comment by saliceti** [comment] 2020-09-25 13:51
We can't really use `TF_LOG=trace` as it runs in public repos and it will expose a bunch of secrets. We'll think of something or try to reproduce locally.
You can see failures in 2 different repos, but similar terraform code:
https://github.com/DFE-Digital/get-into-teaching-content/runs/1144486580?check_suite_focus=true
https://github.com/DFE-Digital/get-into-teaching-content/runs/1154422512?check_suite_focus=true
https://github.com/DFE-Digital/teacher-vacancy-service/runs/1111221308?check_suite_focus=true

Most of the time it takes less than 1 minute and runs fine:
https://github.com/DFE-Digital/get-into-teaching-content/runs/1160429213?check_suite_focus=true

**Comment by saliceti** [comment] 2020-09-28 10:40
Interestingly it does look related to app start timeout. We bumped it to 3min and pushed an app that fails to start (failing http healthcheck). It failed with rpc error after 3min:
https://github.com/DFE-Digital/teacher-vacancy-service/runs/1175917293?check_suite_focus=true

**Comment by saliceti** [comment] 2020-10-05 17:03
@46bit @ArthurHlt : It was too long to sanitise our output but I've managed to reproduce it with a simple test case: https://github.com/saliceti/test-tf-cf-rpc-error-2

Setup:
- Create .tfvars file or use TF_VARs: api_url, org, space, domain
- Use SSO passcode or user/password
- Run terraform apply, it should deploy nginx

To make it fail, use the examples commented out:
- Swap the nginx docker image to force redeploy
- Change the healthcheck path to make it fail
- Or change the timeout to make it fail

You should get error: `Error: rpc error: code = Unavailable desc = transport is closing`
And a crash.log

**Comment by saliceti** [comment] 2020-10-05 17:25
Here is the error (For crash.log and trace, run the above):
```
$ terraform apply -auto-approve                                                                                                                                     
data.cloudfoundry_domain.domain: Refreshing state... [id=86484fb4-8d55-4f24-a3af-eda030b95ad8]
data.cloudfoundry_org.org: Refreshing state... [id=386a9502-d9b6-4aba-b3c3-ebe4fa3f963e]
data.cloudfoundry_space.space: Refreshing state... [id=934ff889-4644-46b3-afb2-79f47c558c73]
cloudfoundry_route.web_app_route: Refreshing state... [id=e165ffa5-44ea-4c56-b9c1-a274ecfc01ef]
cloudfoundry_app.web_app: Refreshing state... [id=0d2fa87d-f647-4943-b905-6f7315e55e57]
cloudfoundry_app.web_app: Modifying... [id=0d2fa87d-f647-4943-b905-6f7315e55e57]
cloudfoundry_app.web_app: Still modifying... [id=0d2fa87d-f647-4943-b905-6f7315e55e57, 10s elapsed]

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: index out of range [0] with length 0
2020-10-05T18:02:46.392+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: 
2020-10-05T18:02:46.392+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: goroutine 30 [running]:
2020-10-05T18:02:46.392+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers.BlueGreenV2.Restage.func5(0xc00085a150, 0xc00085a150, 0x0, 0x0)
2020-10-05T18:02:46.392+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: 	github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers/bluegreenv2_strategy.go:152 +0x428
2020-10-05T18:02:46.392+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers.Actions.Execute(0xc000869908, 0x5, 0x5, 0x2befbe0, 0x0, 0x0)
2020-10-05T18:02:46.392+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: 	github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers/rewind.go:219 +0x86
2020-10-05T18:02:46.392+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers.BlueGreenV2.Restage(0xc0004aa4a0, 0xc0005fc000, 0xc000466100, 0xc000488200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2020-10-05T18:02:46.392+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: 	github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers/bluegreenv2_strategy.go:166 +0x3e8
2020-10-05T18:02:46.392+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry.resourceAppUpdate(0xc0001dd180, 0x1e90b00, 0xc0005fac80, 0x0, 0x0)
2020-10-05T18:02:46.392+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: 	github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/resource_cf_app.go:540 +0xa3e
2020-10-05T18:02:46.392+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00043de60, 0xc000497310, 0xc000297400, 0x1e90b00, 0xc0005fac80, 0x1deb801, 0xc0006bb890, 0xc00082c240)
2020-10-05T18:02:46.392+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/resource.go:316 +0x263
2020-10-05T18:02:46.392+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00010c000, 0xc0006bba10, 0xc000497310, 0xc000297400, 0xc000818088, 0xc00000e708, 0x1dee380)
2020-10-05T18:02:46.392+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/provider.go:294 +0x99
2020-10-05T18:02:46.392+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000e4d0, 0x22774e0, 0xc000203d40, 0xc0001dc230, 0xc00000e4d0, 0xc000203d40, 0xc0001fbb78)
2020-10-05T18:02:46.392+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/helper/plugin/grpc_provider.go:885 +0x8b4
2020-10-05T18:02:46.392+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1f571a0, 0xc00000e4d0, 0x22774e0, 0xc000203d40, 0xc00044eea0, 0x0, 0x22774e0, 0xc000203d40, 0xc000351500, 0x64f)
2020-10-05T18:02:46.392+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x217
2020-10-05T18:02:46.393+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000682780, 0x2285880, 0xc000683800, 0xc000708400, 0xc000202a80, 0x2ba7e80, 0x0, 0x0, 0x0)
2020-10-05T18:02:46.393+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: 	google.golang.org/grpc@v1.27.1/server.go:1024 +0x501
2020-10-05T18:02:46.393+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: google.golang.org/grpc.(*Server).handleStream(0xc000682780, 0x2285880, 0xc000683800, 0xc000708400, 0x0)
2020-10-05T18:02:46.393+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: 	google.golang.org/grpc@v1.27.1/server.go:1313 +0xd3d
2020-10-05T18:02:46.393+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00020a570, 0xc000682780, 0x2285880, 0xc000683800, 0xc000708400)
2020-10-05T18:02:46.393+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: 	google.golang.org/grpc@v1.27.1/server.go:722 +0xa1
2020-10-05T18:02:46.393+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-10-05T18:02:46.393+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: 	google.golang.org/grpc@v1.27.1/server.go:720 +0xa1
2020-10-05T18:02:46.395+0100 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020/10/05 18:02:46 [DEBUG] cloudfoundry_app.web_app: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/10/05 18:02:46 [TRACE] eval: *terraform.EvalMaybeTainted
2020/10/05 18:02:46 [TRACE] eval: *terraform.EvalWriteState
2020/10/05 18:02:46 [TRACE] EvalWriteState: recording 2 dependencies for cloudfoundry_app.web_app
2020/10/05 18:02:46 [TRACE] EvalWriteState: writing current state object for cloudfoundry_app.web_app
2020-10-05T18:02:46.395+0100 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/cloudfoundry-community/cloudfoundry/0.12.4/darwin_amd64/terraform-provider-cloudfoundry_v0.12.4 pid=8940 error="exit status 2"
2020/10/05 18:02:46 [TRACE] eval: *terraform.EvalApplyProvisioners
2020/10/05 18:02:46 [TRACE] EvalApplyProvisioners: cloudfoundry_app.web_app is not freshly-created, so no provisioning is required
2020/10/05 18:02:46 [TRACE] eval: *terraform.EvalMaybeTainted
2020/10/05 18:02:46 [TRACE] eval: *terraform.EvalWriteState
2020/10/05 18:02:46 [TRACE] EvalWriteState: recording 2 dependencies for cloudfoundry_app.web_app
2020/10/05 18:02:46 [TRACE] EvalWriteState: writing current state object for cloudfoundry_app.web_app
2020/10/05 18:02:46 [TRACE] eval: *terraform.EvalIf
2020/10/05 18:02:46 [TRACE] eval: *terraform.EvalIf
2020/10/05 18:02:46 [TRACE] eval: *terraform.EvalWriteDiff
2020/10/05 18:02:46 [TRACE] eval: *terraform.EvalApplyPost
2020/10/05 18:02:46 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2020/10/05 18:02:46 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/10/05 18:02:46 [TRACE] [walkApply] Exiting eval tree: cloudfoundry_app.web_app
2020/10/05 18:02:46 [TRACE] vertex "cloudfoundry_app.web_app": visit complete
2020/10/05 18:02:46 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/10/05 18:02:46 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/cloudfoundry-community/cloudfoundry\"] (close)" errored, so skipping
2020/10/05 18:02:46 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/10/05 18:02:46 [TRACE] statemgr.Filesystem: creating backup snapshot at terraform.tfstate.backup
2020/10/05 18:02:46 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 29
2020/10/05 18:02:46 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2020/10/05 18:02:46 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2020/10/05 18:02:46 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2020-10-05T18:02:46.408+0100 [DEBUG] plugin: plugin exited
```

**Comment by ArthurHlt** [comment] 2020-10-05 18:53
Thanks you for the hard work @saliceti 
This is due to bad error handling on [/cloudfoundry/managers/appdeployers/bluegreenv2_strategy.go:144](/cloudfoundry/managers/appdeployers/bluegreenv2_strategy.go:144) which let try to get the content of a slice just after. 

So, yes here it actually should come from a timeout error not catched. This is happening only on docker because this slice is always filled with standard cloud foundry behavior.

I will fix it this will let you have the real timeout error and the logs associated on what happened 

Thanks to everyone

**Comment by sfawcett123** [comment] 2020-10-08 09:06
Just to add , we ran a deployment today, and it failed in a few seconds.

`Acquiring state lock. This may take a few moments...
cloudfoundry_app.app_application: Modifying... [id=bb6e8d3d-3714-43df-af89-c27ca8f13a3f]
cloudfoundry_app.app_application: Still modifying... [id=bb6e8d3d-3714-43df-af89-c27ca8f13a3f, 10s elapsed]
Error: rpc error: code = Unavailable desc = transport is closing`

If you notice the error was within 10 seconds. The timeout is set to 180 seconds.

`
resource "cloudfoundry_app" "app_application" {
    name         = var.paas_app_application_name
    space        = data.cloudfoundry_space.space.id
    docker_image = var.paas_app_docker_image
    strategy     = var.strategy
    memory     = 1024
    timeout      = 180
    instances   = 1
     ........
`
variable "strategy" {
   default = "blue-green"
}

It then produced a **-vernerables** which subsequently stopped all further deployments. until I tidied it up. 

There are two problems I feel need to be resolved

1. The Error being reported always states it is an RPC error, regardless of whether it is or not, it could well be a code problem with the container, not starting, or something with Cloud Foundry. but the same error for each problem isn't helping us.

2. The -venerables being left behind, is causing the system to stop delivery. which is a bit of a show stopper.

**Comment by ArthurHlt** [comment] 2020-10-08 09:11
This is still linked to the fix made just before, you have probably an error during starting but you actually can't see it or have a cleaning cause of improper error handling

**Closed** 2020-10-08 09:33 UTC

**Comment by ArthurHlt** [comment] 2020-10-08 10:15
You can now use the provider in version 0.12.5:

```
terraform {
  required_providers {
    cloudfoundry = {
      source = "cloudfoundry-community/cloudfoundry"
      version = "0.12.5"
    }
  }
}
```

**Comment by saliceti** [comment] 2020-10-08 13:49
Hi @ArthurHlt . I tried the test case above with the new plugin but I'm getting an error:

```
data.cloudfoundry_domain.domain: Refreshing state... [id=86484fb4-8d55-4f24-a3af-eda030b95ad8]
data.cloudfoundry_org.org: Refreshing state... [id=386a9502-d9b6-4aba-b3c3-ebe4fa3f963e]
data.cloudfoundry_space.space: Refreshing state... [id=934ff889-4644-46b3-afb2-79f47c558c73]
cloudfoundry_route.web_app_route: Refreshing state... [id=e165ffa5-44ea-4c56-b9c1-a274ecfc01ef]
cloudfoundry_app.web_app: Refreshing state... [id=0d2fa87d-f647-4943-b905-6f7315e55e57]
cloudfoundry_app.web_app: Modifying... [id=0d2fa87d-f647-4943-b905-6f7315e55e57]
cloudfoundry_app.web_app: Still modifying... [id=0d2fa87d-f647-4943-b905-6f7315e55e57, 10s elapsed]

Error: rpc error: code = Unavailable desc = transport is closing


panic: interface conversion: interface {} is nil, not appdeployers.AppDeployResponse
2020-10-08T14:45:46.896+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: 
2020-10-08T14:45:46.896+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: goroutine 132 [running]:
2020-10-08T14:45:46.896+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers.BlueGreenV2.Restage.func1(0x0, 0x0, 0x2252d60)
2020-10-08T14:45:46.896+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: 	github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers/bluegreenv2_strategy.go:88 +0x28e
2020-10-08T14:45:46.896+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers.Actions.Execute(0xc00099b908, 0x5, 0x5, 0x2befbe0, 0x0, 0x0)
2020-10-08T14:45:46.896+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: 	github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers/rewind.go:225 +0xf8
2020-10-08T14:45:46.896+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers.BlueGreenV2.Restage(0xc000229fe0, 0xc00051e480, 0xc0006f8320, 0xc00026c6a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2020-10-08T14:45:46.896+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: 	github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers/bluegreenv2_strategy.go:169 +0x3e8
2020-10-08T14:45:46.896+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry.resourceAppUpdate(0xc00015f5e0, 0x1e90b40, 0xc0000e6b40, 0x0, 0x0)
2020-10-08T14:45:46.896+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: 	github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/resource_cf_app.go:540 +0xa3e
2020-10-08T14:45:46.896+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000560d80, 0xc00020c230, 0xc000166f40, 0x1e90b40, 0xc0000e6b40, 0x1deb801, 0xc000445890, 0xc000926930)
2020-10-08T14:45:46.896+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/resource.go:316 +0x263
2020-10-08T14:45:46.896+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000158980, 0xc000445a10, 0xc00020c230, 0xc000166f40, 0xc000910868, 0xc0000a4270, 0x1dee3c0)
2020-10-08T14:45:46.896+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/provider.go:294 +0x99
2020-10-08T14:45:46.896+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000ee00, 0x2277280, 0xc00076c8d0, 0xc00015e380, 0xc00000ee00, 0xc00076c8d0, 0xc0004a9b78)
2020-10-08T14:45:46.896+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/helper/plugin/grpc_provider.go:885 +0x8b4
2020-10-08T14:45:46.896+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1f571e0, 0xc00000ee00, 0x2277280, 0xc00076c8d0, 0xc00074e900, 0x0, 0x2277280, 0xc00076c8d0, 0xc000319c00, 0x64f)
2020-10-08T14:45:46.897+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x217
2020-10-08T14:45:46.897+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001e00, 0x2285620, 0xc000783500, 0xc000590400, 0xc000177560, 0x2ba7e80, 0x0, 0x0, 0x0)
2020-10-08T14:45:46.897+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: 	google.golang.org/grpc@v1.27.1/server.go:1024 +0x501
2020-10-08T14:45:46.897+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: google.golang.org/grpc.(*Server).handleStream(0xc000001e00, 0x2285620, 0xc000783500, 0xc000590400, 0x0)
2020-10-08T14:45:46.897+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: 	google.golang.org/grpc@v1.27.1/server.go:1313 +0xd3d
2020-10-08T14:45:46.897+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000414200, 0xc000001e00, 0x2285620, 0xc000783500, 0xc000590400)
2020-10-08T14:45:46.897+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: 	google.golang.org/grpc@v1.27.1/server.go:722 +0xa1
2020-10-08T14:45:46.897+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-10-08T14:45:46.897+0100 [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.5: 	google.golang.org/grpc@v1.27.1/server.go:720 +0xa1
2020-10-08T14:45:46.900+0100 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020/10/08 14:45:46 [DEBUG] cloudfoundry_app.web_app: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/10/08 14:45:46 [TRACE] eval: *terraform.EvalMaybeTainted
2020/10/08 14:45:46 [TRACE] eval: *terraform.EvalWriteState
2020/10/08 14:45:46 [TRACE] EvalWriteState: recording 2 dependencies for cloudfoundry_app.web_app
2020/10/08 14:45:46 [TRACE] EvalWriteState: writing current state object for cloudfoundry_app.web_app
2020-10-08T14:45:46.900+0100 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/cloudfoundry-community/cloudfoundry/0.12.5/darwin_amd64/terraform-provider-cloudfoundry_v0.12.5 pid=7234 error="exit status 2"
2020/10/08 14:45:46 [TRACE] eval: *terraform.EvalApplyProvisioners
2020/10/08 14:45:46 [TRACE] EvalApplyProvisioners: cloudfoundry_app.web_app is not freshly-created, so no provisioning is required
2020/10/08 14:45:46 [TRACE] eval: *terraform.EvalMaybeTainted
2020/10/08 14:45:46 [TRACE] eval: *terraform.EvalWriteState
2020/10/08 14:45:46 [TRACE] EvalWriteState: recording 2 dependencies for cloudfoundry_app.web_app
2020/10/08 14:45:46 [TRACE] EvalWriteState: writing current state object for cloudfoundry_app.web_app
2020/10/08 14:45:46 [TRACE] eval: *terraform.EvalIf
2020/10/08 14:45:46 [TRACE] eval: *terraform.EvalIf
2020/10/08 14:45:46 [TRACE] eval: *terraform.EvalWriteDiff
2020/10/08 14:45:46 [TRACE] eval: *terraform.EvalApplyPost
2020/10/08 14:45:46 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2020/10/08 14:45:46 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/10/08 14:45:46 [TRACE] [walkApply] Exiting eval tree: cloudfoundry_app.web_app
2020/10/08 14:45:46 [TRACE] vertex "cloudfoundry_app.web_app": visit complete
2020/10/08 14:45:46 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/10/08 14:45:46 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/cloudfoundry-community/cloudfoundry\"] (close)" errored, so skipping
2020/10/08 14:45:46 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/10/08 14:45:46 [TRACE] statemgr.Filesystem: creating backup snapshot at terraform.tfstate.backup
2020/10/08 14:45:46 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 33
2020/10/08 14:45:46 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2020/10/08 14:45:46 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2020/10/08 14:45:46 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2020-10-08T14:45:46.916+0100 [DEBUG] plugin: plugin exited
```

**Comment by ArthurHlt** [comment] 2020-10-08 15:12
@saliceti Thanks for the catch, sorry for the new issue, i've advertised on release 0.12.5 to not be used.

You can switch on 0.12.6:

```
terraform {
  required_providers {
    cloudfoundry = {
      source = "cloudfoundry-community/cloudfoundry"
      version = "0.12.6"
    }
  }
}
```

**Comment by saliceti** [comment] 2020-10-08 16:47
Indeed I confirm it works perfectly on 0.12.6. Thanks a lot @ArthurHlt !
